AllCops:
  Exclude:
    - 'db/**/*'
    - 'Gemfile'
    - 'vendor/*'
    - '**/.asdf/*'
    - 'config/initializers/devise.rb'
    - 'bin/*'
  NewCops: enable
    
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

# This is handled by Metrics/ABCSize
Metrics/MethodLength:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-capybara