AllCops:
  Exclude:
    - 'db/**/*'
    
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyle: consistent_comma

Style/MethodLength:
  Enabled: false