AllCops:
  Exclude:
    - 'db/**/*'
    - 'Gemfile'
    - 'vendor/*'
    - '**/.asdf/*'
    
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyle: consistent_comma

Style/MethodLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented